import React from 'react'
import Head from 'next/head'
import HeroSection from '@/components/HeroSection'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Link from 'next/link'
export default function index() {
    return (
        <div>
            <html>
                <Head>
                    <title>Ken Jayakusuma</title>
                    <meta content="width=device-width, initial-scale=1" name="viewport" />
                    <meta name="description" content="Generated by create next app" />
                    <Link
                        rel="icon"
                        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
                        />
                </Head>
                <body className='trasition'>
                    <Navbar></Navbar>
                    <main className="mx-auto max-w-3xl px-4 sm:px-6 md:max-w-5xl ">
                        <HeroSection />
                    </main>
                    <Footer></Footer>
                </body>
            </html>
        </div>
    )
}
